langchain4j:
  open-ai:
    chat-model:
      # 课程测试 KEY，需要更换为实际可用 KEY
      api-key: ${AI_DASHSCOPE_API_KEY}
      model-name: qwen-turbo
      # 百炼兼容OpenAI接口规范，base_url为https://dashscope.aliyuncs.com/compatible-mode/v1
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1

server:
  port: 20001
